### ISSUE TITLE
weird character for hill

### ISSUE THREAD

**Issue by tangor86** [m-rtin/anki-ipa#44]
For the hill I get IPA like this:
![image](https://user-images.githubusercontent.com/1785921/183246364-88286831-e599-4c2a-b95a-62f7f0ed7948.png)

IPA:
**hɪɫ**

last character which I assumed should have been "l" is a bit weird (ɫ)... should it be like that?

At one website I get IPA for the same word like this: **hɪl**

**Comment by tangor86** [comment]
and also "r" seems to be upside down:
![image](https://user-images.githubusercontent.com/1785921/183246572-5e0fa850-39a7-4edd-a3aa-c9e6a116b676.png)

**Comment by m-rtin** [comment]
I fixed it, please update the addon:
<img width="760" alt="image" src="https://user-images.githubusercontent.com/46455311/183250305-bba2b05b-d7fb-40e2-a83a-b06bd1140317.png">

The data comes from [here](https://en.wiktionary.org/wiki/regard). They use ɹ instead of r. But it got the American transcription wrong, so I fixed it:
<img width="764" alt="image" src="https://user-images.githubusercontent.com/46455311/183250574-dc633497-86b4-4a3f-93d2-0161b513b961.png">
